name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip zip unzip
        pip3 install buildozer cython
    
    - name: Fix buildozer.spec pour app.py
      run: |
        sed -i 's/source.main = main.py/source.main = app.py/g' buildozer.spec
        sed -i 's/android.ndk = 23b/android.ndk = 25b/g' buildozer.spec
        sed -i 's/android.api = 31/android.api = 33/g' buildozer.spec
        sed -i 's/log_level = 1/log_level = 2/g' buildozer.spec
    
    - name: Build with Buildozer
      run: buildozer -v android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: doctorfrio-apk
        path: bin/*.apk
